import { NextRequest, NextResponse } from "next/server";
// eslint-disable-next-line @typescript-eslint/no-require-imports
const pdfParse = require("pdf-parse");
import { PaperDocument } from "@/lib/types";

export const maxDuration = 60; // Next.js edge/serverless max duration

export async function POST(req: NextRequest) {
  try {
    const formData = await req.formData();
    const file = formData.get("file") as File;

    if (!file) {
      return NextResponse.json({ error: "No file uploaded" }, { status: 400 });
    }

    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    
    let text = "";
    if (file.type === "application/pdf" || file.name.endsWith(".pdf")) {
       const data = await pdfParse(buffer);
       text = data.text;
    } else {
       // Assume it's a text file
       text = buffer.toString("utf-8");
    }

    // Limit text length to prevent excessively long responses if needed, but Gemini 1.5 Flash can handle 1M.
    // We'll limit to first 30,000 characters just to be safe for response speed.
    const truncatedText = text.slice(0, 40000); 

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      // Fallback for demonstration when no API key is provided
      const fallbackPaper: PaperDocument = {
        id: "demo-uploaded-paper",
        title: "Demo: Uploaded Document Analysis",
        authors: "HyperPaper User",
        published: "Just Now",
        venue: "Local Hackathon",
        readingTimeMinutes: 5,
        executiveSummary: "This is a demonstration of the document analysis pipeline running in fallback mode because no GEMINI_API_KEY was found in the environment. It successfully extracted text from your file and rendered this mockup.",
        concepts: [
          {
            id: "extracted-concept-1",
            name: "Extracted Concept",
            color: "#ec4899",
            aliases: ["concept", "extracted concept"],
            operationalDefinition: "A demonstration concept automatically generated by the fallback pipeline.",
            dictionaryContrast: "Unlike a real AI extraction, this is hardcoded.",
            eli5: "It's like a placeholder image when a website is loading.",
            significance: "Proves that the upload, parsing, and rendering pipeline works end-to-end.",
            category: "mechanism",
            firstIntroducedSectionId: "sec-1",
            relations: []
          }
        ],
        sections: [
          {
            id: "sec-1",
            number: "1",
            title: "Extracted Text (Preview)",
            content: [
              truncatedText.slice(0, 1500) + (truncatedText.length > 1500 ? "..." : "")
            ]
          }
        ]
      };
      
      // Artificial delay to simulate processing
      await new Promise(resolve => setTimeout(resolve, 1500));
      return NextResponse.json(fallbackPaper);
    }

    const prompt = `You are HyperPaper AI, an expert academic reader. 
I am providing you with the text of an academic paper or document. 
Your task is to analyze it and convert it into a highly structured JSON format.

DOCUMENT TEXT:
================
${truncatedText}
================

INSTRUCTIONS:
Extract the document into the following strict JSON schema (representing the PaperDocument interface):
{
  "id": "generate-a-kebab-case-id-based-on-title",
  "title": "Exact Title of the Document",
  "authors": "Author names (if none found, say 'Unknown')",
  "published": "Publication date or venue (if none, say 'Unknown')",
  "venue": "Venue or publisher (if none, say 'Unknown')",
  "readingTimeMinutes": <number, estimate based on length>,
  "executiveSummary": "A punchy, 2-3 sentence summary of what this document is about.",
  "concepts": [
    {
      "id": "concept-kebab-case",
      "name": "Canonical Name of Concept (e.g. Self-Attention)",
      "color": "Pick a visually distinct hex color like #6366f1, #ec4899, #10b981",
      "aliases": ["alias1", "alias2"],
      "operationalDefinition": "How this concept is specifically used in this text.",
      "dictionaryContrast": "How it differs from standard dictionary definition.",
      "eli5": "Explain Like I'm 5 analogy.",
      "significance": "Why it matters.",
      "category": "core-primitive",
      "firstIntroducedSectionId": "sec-1",
      "relations": [
        {
          "targetConceptId": "another-concept-id",
          "relationType": "e.g. implements, optimizes, critiques",
          "description": "How they relate"
        }
      ]
    }
  ],
  "sections": [
    {
      "id": "sec-1",
      "number": "1",
      "title": "Title of section (e.g. Introduction)",
      "content": [
        "Paragraph 1 text...",
        "Paragraph 2 text..."
      ]
    }
  ]
}

CRITICAL RULES:
1. Extract at least 3-5 major concepts.
2. Group the text into 3-6 logical sections. Clean up any weird PDF artifacts, line breaks, or page numbers in the paragraph content.
3. Make sure 'targetConceptId' in relations actually matches an 'id' in your concepts array!
4. RETURN ONLY VALID JSON. No markdown backticks, no comments. Just the JSON object starting with { and ending with }.`;

    const geminiRes = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: { 
            responseMimeType: "application/json",
            temperature: 0.1
          },
        }),
      }
    );

    if (!geminiRes.ok) {
      const errText = await geminiRes.text();
      console.error("Gemini API error:", errText);
      return NextResponse.json({ error: "Failed to process document with AI" }, { status: 500 });
    }

    const geminiData = await geminiRes.json();
    const resText = geminiData.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!resText) {
       return NextResponse.json({ error: "No response from AI" }, { status: 500 });
    }

    // Try parsing the JSON
    const parsedData = JSON.parse(resText) as PaperDocument;
    
    return NextResponse.json(parsedData);

  } catch (error) {
    console.error("Upload processing error:", error);
    return NextResponse.json({ error: "Internal server error during upload" }, { status: 500 });
  }
}
